[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

# Compression sozlamalari - ERR_CONTENT_DECODING_FAILED xatosini hal qilish uchun
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "gzip"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "gzip"
    Cache-Control = "public, max-age=31536000"

# SPA routing uchun redirect qoidasi
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "br"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

